name: Java CI with gradlew
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
# actions/checkout@v3는 커밋이 되었을 때 러너쪽으로 소스코드 복사
    steps:
      - name : 체크아웃 레포지토리
        uses : actions/checkout@v3
# 러너에 자바 환경이 없는 경우 java 17버전으로 gradle 도구를 포함해 설치
      - name: 자바 환경 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
# Gradlew는 실행권한이 없으면 실행이 안되므로 권한 부여 후 실행
      - name: Gradlew에 대한 실행 권한 부여
        run: chmod +x ./gradlew
# Gradle로 빌드 해보기 (테스트 과정까지 수행됨)
      - name: Build with Gradle
        run: ./gradlew build